# --- Basic Bindings ---
bindsym $mod+Shift+Space floating toggle
bindsym $mod+Space focus mode_toggle
bindsym $mod+Escape workspace prev

# --- Hide Everything ---
bindsym $mod+Shift+Delete exec --no-startup-id lmc truemute ; exec --no-stattup-id lmc pause ; exec --no-startup-id pauseallmpv; workspace 0; exec $term -e htop ; exec $term -e $file

# --- Letter Key ---
bindsym $mod+q [con_id="__focused__" instance="^(?!dropdown_).*$"] kill
bindsym $mod+Shift+q [con_id="__focused__" instance="^(?!dropdown_).*$"] exec --no-startup-id kill -9 `xdotool getwindowfocus getwindowpid`
bindsym $mod+Shift+r exec --no-startup-id winresize
bindsym $mod+t split toggle
bindsym $mod+Shift+t gaps inner current set 10; gaps current set 10

bindsym $mod+y resize grow left
bindsym $mod+Shift+y resize shrink left
bindsym $mod+u resize grow height
bindsym $mod+Shift+u resize shrink height
bindsym $mod+i resize grow width
bindsym $mod+Shift+i resize shrink width
bindsym $mod+o resize grow right
bindsym $mod+Shift+o resize shrink right

bindsym $mod+Ctrl+o sticky toggle

bindsym $mod+s gaps inner current plus 5
bindsym $mod+Shift+s gaps inner current minus 5

bindsym $mod+a gaps inner current set 0; gaps outer current set 0

bindsym $mod+d exec --no-startup-id dmenu_run -nb "#1E1E2E" -nf "#CDD6F4" -sb "#89B4F4" -sf "#1E1E2E"

set $freeze Distraction-free mode
mode "$freeze" { bindsym $mod+Shift+f mode "default"
}

bindsym $mod+f fullscreen toggle
bindsym $mod+Shift+f mode "$freeze" ;; exec --no-startup-id notify-send "Distraction-free mode activated." "Press Super+Shift+f to return"

bindsym $mod+g workspace prev

bindsym $mod+h focus left
bindsym $mod+Shift+h move left 30
bindsym $mod+Ctrl+h move workspace to output left

bindsym $mod+j focus down
bindsym $mod+Shift+j move down 30
bindsym $mod+Ctrl+j move workspace to output down

bindsym $mod+k focus up
bindsym $mod+Shift+k move up 30
bindsym $mod+Ctrl+k move workspace to output up

bindsym $mod+l focus right
bindsym $mod+Shift+l move right 30
bindsym $mod+Ctrl+l move workspace to output right

bindsym $mod+z gaps outer current plus 5
bindsym $mod+Shift+z gaps outer current minus 5

bindsym $mod+b bar mode toggle
bindsym $mod+Shift+b floating toggle; sticky toggle; exec --no-startup-id hover left

bindsym $mod+Shift+n floating toggle; sticky toggle; exec --no-startup-id hover right

bindsym Print exec "flameshot gui"

bindsym $mod+Shift+d exec --no-startup-id kitty -e ranger

bindsym $mod+x exec --no-startup-id kitty -e pulsemixer

bindsym $mod+p exec dunstctl history-pop

bindsym $mod+v exec --no-startup-id ~/.config/i3/scripts/clipboard.sh
bindsym $mod+Shift+v exec rm -f /run/user/clipmenu*.*/line_cache

# --- Workspace Bind ---
bindsym $mod+Home               workspace $ws1
bindsym $mod+Shift+Home         move container to workspace $ws1
bindsym $mod+End                workspace $ws10
bindsym $mod+Shift+End          move container to workspace $ws10
bindsym $mod+Prior             workspace prev
bindsym $mod+Shift+Prior       move container to workspace prev
bindsym $mod+Next              workspace next
bindsym $mod+Shift+Next                move container to workspace next
bindsym $mod+Tab                workspace back_and_forth
bindsym $mod+XF86AudioPrev          workspace prev
bindsym $mod+Shift+XF86AudioPrev    move container to workspace prev
bindsym $mod+XF86AudioNext       workspace next
bindsym $mod+Shift+XF86AudioNext move container to workspace next
bindsym $mod+semicolon          workspace next
bindsym $mod+apostrophe         split horizontal ;; exec $term
bindsym $mod+slash              split vertical ;; exec $term
bindsym $mod+Shift+slash        kill
bindsym $mod+backslash          workspace back_and_forth

# --- Function Keys ---
bindsym XF86MonBrightnessUp exec brightnessctl set +5%
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-

bindsym $mod+F6 workspace 6; exec kicad
bindsym $mod+F8 workspace 8; exec code
