exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id polkit-kde-authentication-agent-1
exec --no-startup-id picom --config $HOME/.config/picom/picom.conf -b
exec --no-startup-id xss-lock --transfer-sleep-lock betterlockscreen -l dimblur

exec --no-startup-id nm-applet
exec --no-startup-id blueberry-tray
exec --no-startup-id dunst

exec --no-startup-id ~/.config/i3/scripts/start-clipmenud.sh

exec_always ~/.config/polybar/launch.sh &
exec_always feh --bg-fill /home/tan1sh/Pictures/Mikan/Renyan_Final_26.04.26_Preview.png
