
#class			border	background text	   indicator child_border
client.focused		#89B4FA	#89B4FA	   #1E1E2E #F38BA8   #89B4FA
client.focused_inactive	#3A3D4F	#3A3D4F	   #CDD6F4 #3A3D4F   #3A3D4F
client.unfocused	#1E1E2E	#1E1E2E    #A6ADC8 #1E1E2E   #1E1E2E
client.urgent		#F38BA8 #F38BA8	   #1E1E2E #89B4FA   #F38BA8
client.placeholder	#3A3D4F	#1E1E2E	   #6C7086 #3A3D4F   #3A3D4F

client.background	#1E1E2E
