for_window [class="^.*"] border pixel 2
gaps inner 10
gaps outer 10

for_window [instance="dropdown_*"] floating enable
for_window [instance="dropdown_*"] move scratchpad
for_window [instance="dropdown_*"] sticky enable
for_window [instance="dropdown_*"] scratchpad show
for_window [instance="dropdown_*"] move position center

for_window [instance="dropdown_kitty"] resize set 625 450
for_window [instance="dropdown_notes"] resize set 450 650

