; Pastel Dark Theme for Polybar
; Dark Background with soft pastel accent

[colors]
background	= #1E1E2E
background-alt	= #3A3D4F
foreground	= #CDD6F4
foreground-alt	= #A6ADC8

; Pastel Accent

red		 = #F38BA8
red-alt		 = #8F4B53
pink		 = #FFC5D3
peach		 = #FAB387
yellow		 = #F9E2AF
lime		 = #E6E23B
green		 = #A6E3A1
teal		 = #94E2D5
blue		 = #89B4FA
indigo		 = #B4BDFE 
purple		 = #EBA0AC
lavender	 = #CBA6F7

; Role Mappings
primary		 = #A6E3A1
secondry 	 = #94E2D5
alert		 = #8F4B53
disabled	 = #6C7086
accent 		 = #89B4F4
